header = """
# Performance Mods
A list of performance-enhancing mods for {loaders} {versions} version.

## Any suggestions/complaints?
> #### Join us on [Discord](https://discord.gg/8nzHYhVUQS).
> Or contact us with your questions [here](./../../issues).

[![Home](https://i.imgur.com/zGuelkW.png)](https://github.com/NordicGamerFE/usefulmods/blob/main/README.md)

## {loaders} {versions}

| Name |  Description | Author | Performance Improvement (Client/Server) | Need help? |
| --- | :---: | :---: | :---: | :---: |
"""
middle = """



## Forge 1.18.X


"""
footer = """

[![Home](https://i.imgur.com/zGuelkW.png)](https://github.com/NordicGamerFE/usefulmods/blob/main/README.md)
"""

links = {
    "temp": [
        450269,
        233019,
        "https://modrinth.com/mod/alternate-current",
        403365,
        "https://modrinth.com/mod/better-beds",
        "https://modrinth.com/mod/better-biome-blend",
        551520,
        582640,
        229876,
        285789,
        "https://modrinth.com/mod/canvas",
        256717,
        230020,
        "https://modrinth.com/mod/cull-leaves",
        "https://modrinth.com/mod/cull-less-leaves",
        362791,
        "https://modrinth.com/mod/dashloader",
        416519,
        543308,
        480816,
        366140,
        409087,
        "https://modrinth.com/mod/entityculling",
        364540,
        364531,
        436038,
        242677,
        299540,
        389989,
        630620,
        475117,
        288885,
        394185,
        "https://modrinth.com/mod/fat-experience-orbs",
        "https://modrinth.com/mod/ferrite-core",
        626476,
        "https://modrinth.com/mod/foamfix",
        411045,
        491233,
        619355,
        "https://modrinth.com/mod/krypton",
        549394,
        "https://modrinth.com/mod/ksyxis",
        460819,
        "https://modrinth.com/mod/lazy-language-loader",
        "https://modrinth.com/mod/lazydfu",
        "https://modrinth.com/mod/lithium",
        372626,
        460609,
        558905,
        "https://modrinth.com/mod/memoryleakfix",
        "https://modrinth.com/mod/moreculling",
        307843,
        624960,
        581495,
        428199,
        401556,
        431157,
        408853,
        354143,
        "https://modrinth.com/mod/phosphor",
        318255,
        533801,
        570017,
        596879,
        473492,
        529754,
        574856,
        "https://modrinth.com/mod/simply-no-shading",
        "https://modrinth.com/mod/smoke-suppression",
        415758,
        420913,
        "https://modrinth.com/mod/sodium",
        532724,
        399022,
        226115,
        225606,
        "https://modrinth.com/mod/starlight",
        "https://modrinth.com/mod/starlight-forge",
        560058,
        250290,
        283344,
        269359,
        301913,
        "https://modrinth.com/mod/vanillafix"
    ],
    '1.18.x-fabric':
        [
            'https://modrinth.com/mod/entityculling',
            'https://modrinth.com/mod/better-biome-blend',
            'https://modrinth.com/mod/alternate-current',
            'https://modrinth.com/mod/cull-leaves',
            'https://modrinth.com/mod/dashloader',
            'https://modrinth.com/mod/ebe',
            'https://modrinth.com/mod/ferrite-core',
            'https://modrinth.com/mod/krypton',
            'https://modrinth.com/mod/lazydfu',
            'https://modrinth.com/mod/lazy-language-loader',
            'https://modrinth.com/mod/lithium',
            'https://modrinth.com/mod/servercore',
            'https://modrinth.com/mod/smoke-suppression',
            'https://modrinth.com/mod/smoothboot-fabric',
            'https://modrinth.com/mod/sodium',
            'https://modrinth.com/mod/starlight',
            'https://modrinth.com/mod/starlight-forge',
            'https://modrinth.com/mod/vmp-fabric',
            'https://modrinth.com/mod/better-beds',
            'https://modrinth.com/mod/c2me-fabric',
            'https://modrinth.com/mod/canvas',
            'https://modrinth.com/mod/dynamic-fps',
            'https://modrinth.com/mod/forgetmechunk',
            'https://modrinth.com/mod/ksyxis',
            'https://modrinth.com/mod/nomobgeneration',
            'https://modrinth.com/mod/observable',
            'https://modrinth.com/mod/phosphor',
            256717,
            473492,
            436038,
            364540,
            366140,
            364531,
            582640,
        ],
    '1.18.x-forge':
        [
            'https://modrinth.com/mod/alternate-current',
            233019,
            551520,
            549394,
            256717,
            366140,
            299540,
            475117,
            537533,
            288885,
            532724,
            'https://modrinth.com/mod/observable',
            570017,
            574856,
            411045,
        ],
    '1.17.x-fabric':
        [
            'https://modrinth.com/mod/alternate-current',
            'https://modrinth.com/mod/cull-leaves',
            'https://modrinth.com/mod/dashloader',
            'https://modrinth.com/mod/ebe',
            'https://modrinth.com/mod/ferrite-core',
            'https://modrinth.com/mod/krypton',
            'https://modrinth.com/mod/lazydfu',
            'https://modrinth.com/mod/lazy-language-loader',
            'https://modrinth.com/mod/lithium',
            'https://modrinth.com/mod/servercore',
            'https://modrinth.com/mod/smoke-suppression',
            'https://modrinth.com/mod/smoothboot-fabric',
            'https://modrinth.com/mod/sodium',
            'https://modrinth.com/mod/starlight',
            'https://modrinth.com/mod/vmp-fabric',
            'https://modrinth.com/mod/better-beds',
            'https://modrinth.com/mod/c2me-fabric',
            'https://modrinth.com/mod/canvas',
            'https://modrinth.com/mod/hydrogen',
            'https://modrinth.com/mod/entity-distance',
            256717,
            364540,
            551520,
            473492,
            436038,
            366140,

        ],
    '1.17.x-forge':
        [
            233019,
            551520,
            256717,
            366140,
            299540,
            475117,
            288885,
            411045,
        ],
}
